# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 540)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #00FFFF;\n"
"    fonf-family: Roboto;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: black;\n"
"    border:     2px solid yellow;\n"
"    border-radius: 10%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    background-color: white;\n"
"    border:     2px solid yellow;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_registration = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_registration.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_registration.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_registration.setObjectName("label_registration")
        self.verticalLayout.addWidget(self.label_registration)
        self.label_login = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_login.setEnabled(True)
        self.lineEdit_login.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.lineEdit_login.setStyleSheet("")
        self.lineEdit_login.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.label_email = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.label_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.label_repeat_the_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_repeat_the_password.setObjectName("label_repeat_the_password")
        self.verticalLayout.addWidget(self.label_repeat_the_password)
        self.lineEdit_repeat_the_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_repeat_the_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_repeat_the_password.setObjectName("lineEdit_repeat_the_password")
        self.verticalLayout.addWidget(self.lineEdit_repeat_the_password)
        self.checkBox_show_password = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_show_password.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.checkBox_show_password.setToolTipDuration(-1)
        self.checkBox_show_password.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBox_show_password.setAutoFillBackground(False)
        self.checkBox_show_password.setObjectName("checkBox_show_password")
        self.verticalLayout.addWidget(self.checkBox_show_password)
        self.pushButton_registration = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_registration.setObjectName("pushButton_registration")
        self.verticalLayout.addWidget(self.pushButton_registration)
        self.label_sign_in = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sign_in.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_sign_in.setStyleSheet("QLabel {\n"
"    color: #800000\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #A52A2A\n"
"}")
        self.label_sign_in.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_sign_in.setObjectName("label_sign_in")
        self.verticalLayout.addWidget(self.label_sign_in)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Регістрація"))
        self.label_registration.setText(_translate("MainWindow", "Реєстрація:"))
        self.label_login.setText(_translate("MainWindow", "Логін:"))
        self.lineEdit_login.setPlaceholderText(_translate("MainWindow", "Логін..."))
        self.label_email.setText(_translate("MainWindow", "Пошта:"))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", "Пошта..."))
        self.label_password.setText(_translate("MainWindow", "Пароль:"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Пароль..."))
        self.label_repeat_the_password.setText(_translate("MainWindow", "Повторити пароль:"))
        self.lineEdit_repeat_the_password.setPlaceholderText(_translate("MainWindow", "Повторити пароль..."))
        self.checkBox_show_password.setText(_translate("MainWindow", "Показати пароль"))
        self.pushButton_registration.setText(_translate("MainWindow", "Зареєструватися"))
        self.label_sign_in.setText(_translate("MainWindow", "Вхід"))
