# Form implementation generated from reading ui file 'restoring_access_to_the_account.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 607)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #00FFFF;\n"
"    fonf-family: Roboto;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: black;\n"
"    border:     2px solid yellow;\n"
"    border-radius: 10%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    background-color: white;\n"
"    border:     2px solid yellow;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_restoring_access_to_the_account = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_restoring_access_to_the_account.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_restoring_access_to_the_account.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_restoring_access_to_the_account.setObjectName("label_restoring_access_to_the_account")
        self.verticalLayout.addWidget(self.label_restoring_access_to_the_account)
        self.label_email = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.label_new_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_new_password.setObjectName("label_new_password")
        self.verticalLayout.addWidget(self.label_new_password)
        self.lineEdit_new_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_new_password.setText("")
        self.lineEdit_new_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.verticalLayout.addWidget(self.lineEdit_new_password)
        self.label_repeat_the_new_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_repeat_the_new_password.setObjectName("label_repeat_the_new_password")
        self.verticalLayout.addWidget(self.label_repeat_the_new_password)
        self.lineEdit_repeat_the_new_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_repeat_the_new_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_repeat_the_new_password.setObjectName("lineEdit_repeat_the_new_password")
        self.verticalLayout.addWidget(self.lineEdit_repeat_the_new_password)
        self.label_enter_the_code_to_change_your_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_enter_the_code_to_change_your_password.setObjectName("label_enter_the_code_to_change_your_password")
        self.verticalLayout.addWidget(self.label_enter_the_code_to_change_your_password)
        self.lineEdit_enter_the_code_to_change_your_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_enter_the_code_to_change_your_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_enter_the_code_to_change_your_password.setObjectName("lineEdit_enter_the_code_to_change_your_password")
        self.verticalLayout.addWidget(self.lineEdit_enter_the_code_to_change_your_password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_show_password = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_show_password.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.checkBox_show_password.setToolTipDuration(-1)
        self.checkBox_show_password.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBox_show_password.setAutoFillBackground(False)
        self.checkBox_show_password.setObjectName("checkBox_show_password")
        self.horizontalLayout.addWidget(self.checkBox_show_password)
        self.checkBox_show_code = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_show_code.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.checkBox_show_code.setToolTipDuration(-1)
        self.checkBox_show_code.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBox_show_code.setAutoFillBackground(False)
        self.checkBox_show_code.setObjectName("checkBox_show_code")
        self.horizontalLayout.addWidget(self.checkBox_show_code)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_change_password = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_change_password.setObjectName("pushButton_change_password")
        self.verticalLayout.addWidget(self.pushButton_change_password)
        self.label_sign_in = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sign_in.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_sign_in.setStyleSheet("QLabel {\n"
"    color: #800000\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #A52A2A\n"
"}")
        self.label_sign_in.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_sign_in.setObjectName("label_sign_in")
        self.verticalLayout.addWidget(self.label_sign_in)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Відновлення доступу до акаунту"))
        self.label_restoring_access_to_the_account.setText(_translate("MainWindow", "Відновлення доступу до акаунту:"))
        self.label_email.setText(_translate("MainWindow", "Пошта:"))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", "Пошта..."))
        self.label_new_password.setText(_translate("MainWindow", "Новий пароль:"))
        self.lineEdit_new_password.setPlaceholderText(_translate("MainWindow", "Новий пароль..."))
        self.label_repeat_the_new_password.setText(_translate("MainWindow", "Повторити новий пароль:"))
        self.lineEdit_repeat_the_new_password.setPlaceholderText(_translate("MainWindow", "Повторити новий пароль..."))
        self.label_enter_the_code_to_change_your_password.setText(_translate("MainWindow", "Введіть код для зміни паролю:"))
        self.lineEdit_enter_the_code_to_change_your_password.setPlaceholderText(_translate("MainWindow", "Введіть код для зміни паролю..."))
        self.checkBox_show_password.setText(_translate("MainWindow", "Показати пароль"))
        self.checkBox_show_code.setText(_translate("MainWindow", "Показати код"))
        self.pushButton_change_password.setText(_translate("MainWindow", "Змінити пароль"))
        self.label_sign_in.setText(_translate("MainWindow", "Вхід"))
