# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 327)
        MainWindow.setMinimumSize(QtCore.QSize(550, 327))
        MainWindow.setMaximumSize(QtCore.QSize(550, 327))
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #00FFFF;\n"
"    fonf-family: Roboto;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: black;\n"
"    border:     2px solid yellow;\n"
"    border-radius: 10%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    background-color: white;\n"
"    border:     2px solid yellow;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_sign_in = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sign_in.sizePolicy().hasHeightForWidth())
        self.label_sign_in.setSizePolicy(sizePolicy)
        self.label_sign_in.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_sign_in.setObjectName("label_sign_in")
        self.verticalLayout_2.addWidget(self.label_sign_in)
        self.label_login = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login.sizePolicy().hasHeightForWidth())
        self.label_login.setSizePolicy(sizePolicy)
        self.label_login.setObjectName("label_login")
        self.verticalLayout_2.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_login.sizePolicy().hasHeightForWidth())
        self.lineEdit_login.setSizePolicy(sizePolicy)
        self.lineEdit_login.setStyleSheet("")
        self.lineEdit_login.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout_2.addWidget(self.lineEdit_login)
        self.label_password = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_password.sizePolicy().hasHeightForWidth())
        self.label_password.setSizePolicy(sizePolicy)
        self.label_password.setObjectName("label_password")
        self.verticalLayout_2.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_password.sizePolicy().hasHeightForWidth())
        self.lineEdit_password.setSizePolicy(sizePolicy)
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_show_password = QtWidgets.QCheckBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_show_password.sizePolicy().hasHeightForWidth())
        self.checkBox_show_password.setSizePolicy(sizePolicy)
        self.checkBox_show_password.setObjectName("checkBox_show_password")
        self.horizontalLayout_2.addWidget(self.checkBox_show_password)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_forgot_password = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forgot_password.sizePolicy().hasHeightForWidth())
        self.label_forgot_password.setSizePolicy(sizePolicy)
        self.label_forgot_password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_forgot_password.setStyleSheet("QLabel {\n"
"    color: #800000\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #A52A2A\n"
"}")
        self.label_forgot_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_forgot_password.setObjectName("label_forgot_password")
        self.horizontalLayout_2.addWidget(self.label_forgot_password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_sign_in = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sign_in.sizePolicy().hasHeightForWidth())
        self.pushButton_sign_in.setSizePolicy(sizePolicy)
        self.pushButton_sign_in.setObjectName("pushButton_sign_in")
        self.verticalLayout.addWidget(self.pushButton_sign_in)
        self.label_registration = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_registration.sizePolicy().hasHeightForWidth())
        self.label_registration.setSizePolicy(sizePolicy)
        self.label_registration.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_registration.setStyleSheet("QLabel {\n"
"    color: #800000\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #A52A2A\n"
"}")
        self.label_registration.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_registration.setObjectName("label_registration")
        self.verticalLayout.addWidget(self.label_registration)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вхід"))
        self.label_sign_in.setText(_translate("MainWindow", "Вхід:"))
        self.label_login.setText(_translate("MainWindow", "Логін:"))
        self.lineEdit_login.setPlaceholderText(_translate("MainWindow", "Логін або email"))
        self.label_password.setText(_translate("MainWindow", "Пароль:"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Пароль..."))
        self.checkBox_show_password.setText(_translate("MainWindow", "Показати пароль"))
        self.label_forgot_password.setText(_translate("MainWindow", "Забули пароль"))
        self.pushButton_sign_in.setText(_translate("MainWindow", "Вхід"))
        self.label_registration.setText(_translate("MainWindow", "Реєстрація"))
